[build]
  command   = "pip install -r requirements.txt"
  functions = "netlify/functions"
  publish   = "public"

[dev]
  functions = "netlify/functions"
  port      = 8888

[functions]
  directory = "netlify/functions"

[functions.runtime]
  python = "python3.12"

[[plugins]]
  package = "netlify-plugin-python"
