[build]
  functions = "netlify/functions"
  publish   = "public"

[dev]
  functions = "netlify/functions"
  port      = 8888

[functions]
  directory = "netlify/functions"

[[plugins]]
  package = "netlify-plugin-python"
