[build]
  # command = "pip install -r requirements.txt"
  publish   = "public"
  functions = "netlify/functions"

[dev]
  functions = "netlify/functions"
  port      = 8888

[functions]
  directory = "netlify/functions"

[[plugins]]
  package = "netlify-plugin-python"
